import React from "react";
export default class Main extends React.Component {
  render() {
    return (
      <div id="mandolin_container" style={{ position: "relative" }}>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          version="1.1"
          baseProfile="full"
          width="100%"
          viewBox="0 0 980 232"
        >
          <line
            stroke="rgb(0,0,0)"
            strokeWidth="7"
            x1="80"
            x2="80"
            y1="59.0"
            y2="211.5"
          />
          <circle cx="255.0" cy="135.0" r="20" fill="rgb(200,200,200)" />
          <text
            dy="0.3em"
            fill="rgb(0,0,0)"
            x="255.0"
            y="135"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
          >
            3
          </text>
          <circle cx="395.0" fill="rgb(200,200,200)" cy="135.0" r="20" />
          <text
            dy="0.3em"
            fill="rgb(0,0,0)"
            x="395.0"
            y="135"
            tyle={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
          >
            5
          </text>
          <circle cx="535.0" fill="rgb(200,200,200)" cy="135.0" r="20" />
          <text
            dy="0.3em"
            fill="rgb(0,0,0)"
            x="535.0"
            y="135"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
          >
            7
          </text>
          <circle cx="745.0" fill="rgb(200,200,200)" cy="135.0" r="20" />
          <text
            dy="0.3em"
            fill="rgb(0,0,0)"
            x="745.0"
            y="135"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
          >
            10
          </text>
          <circle cx="885.0" fill="rgb(200,200,200)" cy="85.0" r="20" />
          <text
            dy="0.3em"
            fill="rgb(0,0,0)"
            x="885.0"
            y="85"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
          >
            12
          </text>
          <circle cx="885.0" fill="rgb(200,200,200)" cy="185.0" r="20" />
          <text
            dy="0.3em"
            fill="rgb(0,0,0)"
            x="885.0"
            y="185"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
          >
            12
          </text>
          <line
            stroke="rgb(150,150,150)"
            stroke-width="3"
            x1="150"
            x2="150"
            y1="60"
            y2="210"
          />
          <line
            stroke="rgb(150,150,150)"
            stroke-width="3"
            x1="220"
            x2="220"
            y1="60"
            y2="210"
          />
          <line
            stroke="rgb(150,150,150)"
            stroke-width="3"
            x1="290"
            x2="290"
            y1="60"
            y2="210"
          />
          <line
            stroke="rgb(150,150,150)"
            stroke-width="3"
            x1="360"
            x2="360"
            y1="60"
            y2="210"
          />
          <line
            stroke="rgb(150,150,150)"
            stroke-width="3"
            x1="430"
            x2="430"
            y1="60"
            y2="210"
          />
          <line
            stroke="rgb(150,150,150)"
            stroke-width="3"
            x1="500"
            x2="500"
            y1="60"
            y2="210"
          />
          <line
            stroke="rgb(150,150,150)"
            stroke-width="3"
            x1="570"
            x2="570"
            y1="60"
            y2="210"
          />
          <line
            stroke="rgb(150,150,150)"
            stroke-width="3"
            x1="640"
            x2="640"
            y1="60"
            y2="210"
          />
          <line
            stroke="rgb(150,150,150)"
            stroke-width="3"
            x1="710"
            x2="710"
            y1="60"
            y2="210"
          />
          <line
            stroke="rgb(150,150,150)"
            stroke-width="3"
            x1="780"
            x2="780"
            y1="60"
            y2="210"
          />
          <line
            stroke="rgb(150,150,150)"
            stroke-width="3"
            x1="850"
            x2="850"
            y1="60"
            y2="210"
          />
          <line
            stroke="rgb(150,150,150)"
            stroke-width="3"
            x1="920"
            x2="920"
            y1="60"
            y2="210"
          />
          <line
            stroke="rgb(0,0,0)"
            stroke-width="2.25"
            x1="78.5"
            x2="921.5"
            y1="60"
            y2="60"
          />
          <line
            stroke="rgb(0,0,0)"
            stroke-width="2.5"
            x1="78.5"
            x2="921.5"
            y1="110"
            y2="110"
          />
          <line
            stroke="rgb(0,0,0)"
            stroke-width="2.75"
            x1="78.5"
            x2="921.5"
            y1="160"
            y2="160"
          />
          <line
            stroke="rgb(0,0,0)"
            stroke-width="3.0"
            x1="78.5"
            x2="921.5"
            y1="210"
            y2="210"
          />
          <circle
            className="C"
            cx="605.0"
            cy="60"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="C"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="605.0"
            y="60"
          >
            C
          </text>
          <circle
            className="C#"
            cx="675.0"
            cy="60"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="C#"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="675.0"
            y="60"
          >
            C#
          </text>
          <circle
            className="D"
            cx="745.0"
            cy="60"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="D"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="745.0"
            y="60"
          >
            D
          </text>
          <circle
            className="E♭"
            cx="815.0"
            cy="60"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="E♭"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="815.0"
            y="60"
          >
            E♭
          </text>
          <circle
            cx="45.0"
            cy="60"
            fill="rgb(255,255,255)"
            r="20"
            stroke="rgb(0,0,0)"
            stroke-width="3"
          />
          <circle
            className="E"
            cx="45.0"
            cy="60"
            fill="rgb(179,71,227)"
            r="20"
            stroke="rgb(0,0,0)"
            stroke-width="3"
          />
          <text
            dy="0.3em"
            fill="rgb(0,0,0)"
            style={{ textAnchor: "middle" }}
            x="45.0"
            y="60"
          >
            E
          </text>
          <circle
            className="F"
            cx="115.0"
            cy="60"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="F"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="115.0"
            y="60"
          >
            F
          </text>
          <circle
            className="F#"
            cx="185.0"
            cy="60"
            fill="rgb(179,71,227)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            r="20"
          />
          <text
            className="F#"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="185.0"
            y="60"
          >
            F#
          </text>
          <circle
            className="G"
            cx="255.0"
            cy="60"
            fill="rgb(179,71,227)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            r="20"
          />
          <text
            className="G"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="255.0"
            y="60"
          >
            G
          </text>
          <circle
            className="A♭"
            cx="325.0"
            cy="60"
            fill="rgb(179,71,227)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            r="20"
          />
          <text
            className="A♭"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="325.0"
            y="60"
          >
            A♭
          </text>
          <circle
            className="A"
            cx="395.0"
            cy="60"
            fill="rgb(179,71,227)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            r="20"
          />
          <text
            className="A"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="395.0"
            y="60"
          >
            A
          </text>
          <circle
            className="B♭"
            cx="465.0"
            cy="60"
            fill="rgb(179,71,227)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            r="20"
          />
          <text
            className="B♭"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="465.0"
            y="60"
          >
            B♭
          </text>
          <circle
            className="B"
            cx="535.0"
            cy="60"
            fill="rgb(179,71,227)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            r="20"
          />
          <text
            className="B"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="535.0"
            y="60"
          >
            B
          </text>
          <circle
            className="C"
            cx="255.0"
            cy="110"
            fill="rgb(179,71,227)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            r="20"
          />
          <text
            className="C"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="255.0"
            y="110"
          >
            C
          </text>
          <circle
            className="C#"
            cx="325.0"
            cy="110"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="C#"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="325.0"
            y="110"
          >
            C#
          </text>
          <circle
            className="D"
            cx="395.0"
            cy="110"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="D"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="395.0"
            y="110"
          >
            D
          </text>
          <circle
            className="E♭"
            cx="465.0"
            cy="110"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="E♭"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="465.0"
            y="110"
          >
            E♭
          </text>
          <circle
            className="E"
            cx="535.0"
            cy="110"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="E"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="535.0"
            y="110"
          >
            E
          </text>
          <circle
            className="F"
            cx="605.0"
            cy="110"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="F"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="605.0"
            y="110"
          >
            F
          </text>
          <circle
            className="F#"
            cx="675.0"
            cy="110"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="F#"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="675.0"
            y="110"
          >
            F#
          </text>
          <circle
            className="G"
            cx="745.0"
            cy="110"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="G"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="745.0"
            y="110"
          >
            G
          </text>
          <circle
            className="A♭"
            cx="815.0"
            cy="110"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="A♭"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="815.0"
            y="110"
          >
            A♭
          </text>
          <circle
            cx="45.0"
            cy="110"
            fill="rgb(255,255,255)"
            r="20"
            stroke="rgb(0,0,0)"
            stroke-width="3"
          />
          <circle
            className="A"
            cx="45.0"
            cy="110"
            fill="rgb(179,71,227)"
            r="20"
            stroke="rgb(0,0,0)"
            stroke-width="3"
          />
          <text
            dy="0.3em"
            fill="rgb(0,0,0)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="45.0"
            y="110"
          >
            A
          </text>
          <circle
            className="B♭"
            cx="115.0"
            cy="110"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="B♭"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="115.0"
            y="110"
          >
            B♭
          </text>
          <circle
            className="B"
            cx="185.0"
            cy="110"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="B"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="185.0"
            y="110"
          >
            B
          </text>
          <circle
            className="C"
            cx="745.0"
            cy="160"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="C"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="745.0"
            y="160"
          >
            C
          </text>
          <circle
            className="C#"
            cx="815.0"
            cy="160"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="C#"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="815.0"
            y="160"
          >
            C#
          </text>
          <circle
            cx="45.0"
            cy="160"
            fill="rgb(255,255,255)"
            r="20"
            stroke="rgb(0,0,0)"
            stroke-width="3"
          />
          <circle
            className="D"
            cx="45.0"
            cy="160"
            fill="rgb(179,71,227)"
            r="20"
            stroke="rgb(0,0,0)"
            stroke-width="3"
          />
          <text
            dy="0.3em"
            fill="rgb(0,0,0)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="45.0"
            y="160"
          >
            D
          </text>
          <circle
            className="E♭"
            cx="115.0"
            cy="160"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="E♭"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="115.0"
            y="160"
          >
            E♭
          </text>
          <circle
            className="E"
            cx="185.0"
            cy="160"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="E"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="185.0"
            y="160"
          >
            E
          </text>
          <circle
            className="F"
            cx="255.0"
            cy="160"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="F"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="255.0"
            y="160"
          >
            F
          </text>
          <circle
            className="F#"
            cx="325.0"
            cy="160"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="F#"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="325.0"
            y="160"
          >
            F#
          </text>
          <circle
            className="G"
            cx="395.0"
            cy="160"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="G"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="395.0"
            y="160"
          >
            G
          </text>
          <circle
            className="A♭"
            cx="465.0"
            cy="160"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="A♭"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="465.0"
            y="160"
          >
            A♭
          </text>
          <circle
            className="A"
            cx="535.0"
            cy="160"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="A"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="535.0"
            y="160"
          >
            A
          </text>
          <circle
            className="B♭"
            cx="605.0"
            cy="160"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="B♭"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="605.0"
            y="160"
          >
            B♭
          </text>
          <circle
            className="B"
            cx="675.0"
            cy="160"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="B"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="675.0"
            y="160"
          >
            B
          </text>
          <circle
            className="C"
            cx="395.0"
            cy="210"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="C"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="395.0"
            y="210"
          >
            C
          </text>
          <circle
            className="C#"
            cx="465.0"
            cy="210"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="C#"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="465.0"
            y="210"
          >
            C#
          </text>
          <circle
            className="D"
            cx="535.0"
            cy="210"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="D"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="535.0"
            y="210"
          >
            D
          </text>
          <circle
            className="E♭"
            cx="605.0"
            cy="210"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="E♭"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="605.0"
            y="210"
          >
            E♭
          </text>
          <circle
            className="E"
            cx="675.0"
            cy="210"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="E"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="675.0"
            y="210"
          >
            E
          </text>
          <circle
            className="F"
            cx="745.0"
            cy="210"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="F"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="745.0"
            y="210"
          >
            F
          </text>
          <circle
            className="F#"
            cx="815.0"
            cy="210"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="F#"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="815.0"
            y="210"
          >
            F#
          </text>
          <circle
            cx="45.0"
            cy="210"
            fill="rgb(255,255,255)"
            r="20"
            stroke="rgb(0,0,0)"
            stroke-width="3"
          />
          <circle
            className="G"
            cx="45.0"
            cy="210"
            fill="rgb(179,71,227)"
            r="20"
            stroke="rgb(0,0,0)"
            stroke-width="3"
          />
          <text
            dy="0.3em"
            fill="rgb(0,0,0)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="45.0"
            y="210"
          >
            G
          </text>
          <circle
            className="A♭"
            cx="115.0"
            cy="210"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="A♭"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="115.0"
            y="210"
          >
            A♭
          </text>
          <circle
            className="A"
            cx="185.0"
            cy="210"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="A"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="185.0"
            y="210"
          >
            A
          </text>
          <circle
            className="B♭"
            cx="255.0"
            cy="210"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="B♭"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="255.0"
            y="210"
          >
            B♭
          </text>
          <circle
            className="B"
            cx="325.0"
            cy="210"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="B"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="325.0"
            y="210"
          >
            B
          </text>
          <circle
            className="E"
            cx="885.0"
            cy="60"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="E"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="885.0"
            y="60"
          >
            E
          </text>
          <circle
            className="A"
            cx="885.0"
            cy="110"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="A"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="885.0"
            y="110"
          >
            A
          </text>
          <circle
            className="D"
            cx="885.0"
            cy="160"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="D"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="885.0"
            y="160"
          >
            D
          </text>
          <circle
            className="G"
            cx="885.0"
            cy="210"
            fill="rgb(179,71,227)"
            r="20"
          />
          <text
            className="G"
            dy="0.3em"
            fill="rgb(255,255,255)"
            style={{ textAnchor: "middle", fontSize: "20", fontWeight: "bold" }}
            x="885.0"
            y="210"
          >
            G
          </text>
        </svg>
      </div>
    );
  }
}
